name: Build python

on:
  push:
    branches:
      - main
  # run pipeline on pull request
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-python:
    permissions:
      contents: write
    env:
      TWINE_USERNAME: ${{ secrets.PYPI_USER }}
      TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: build
        run: pip wheel -v --no-deps -w wheelhouse .

      - name: save version
        id: tag
        run: |
          echo "::set-output name=tag::v$(cat VERSION)"

      - name: test
        run: |
          pip install pybuild-header-dependency[tests]==${{ steps.tag.outputs.tag }} --find-links=wheelhouse
          pytest
      
      - name: Upload wheels
        if: (github.event_name == 'push') || (github.event_name == 'workflow_dispatch')
        run: |
          pip install twine
          echo "Publish to PyPI..."
          twine upload --verbose wheelhouse/*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: (github.event_name == 'push') || (github.event_name == 'workflow_dispatch')
        with:
          files: |
            ./wheelhouse/*.whl
          tag_name: ${{ steps.tag.outputs.tag }}
          prerelease: false
          generate_release_notes: true
          target_commitish: ${{ github.sha }}
